from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from tools.models import AgentCard, PricingPlan, ServiceListing, ServiceProfile, ServicesDocument


TEMPLATE_ROOT = Path(__file__).resolve().parents[1] / "templates"


def generate_listing_assets(
    profile: ServiceProfile,
    pricing: PricingPlan,
    output_dir: str | Path,
) -> list[Path]:
    destination = Path(output_dir)
    destination.mkdir(parents=True, exist_ok=True)

    services = ServicesDocument(
        services=[
            ServiceListing(
                service_id=profile.service_id,
                name=profile.service_name,
                description=(
                    "Paid API conversion generated by Dragon MCP Pay Agent for an "
                    "OKX Marketplace A2MCP provider."
                ),
                endpoint=profile.selected_endpoint.path,
                method=profile.selected_endpoint.method,
                price=str(pricing.amount),
                currency=pricing.currency,
                payment_mode=pricing.payment_mode,
                capabilities=[
                    "A2MCP provider-ready endpoint metadata",
                    "Mock payment verification for review",
                    "Real OKX payment adapter boundary",
                ],
                payment={
                    "mode": pricing.payment_mode,
                    "intendedMode": pricing.intended_mode,
                    "mockHeader": "x-mock-paid: true",
                    "realModeAsset": pricing.real_mode_asset,
                    "requiresSellerCredentials": True,
                },
            )
        ]
    )
    agent_card = AgentCard(
        name="Dragon MCP Pay Agent",
        agent_id="dragon-mcp-pay-agent",
        description=(
            "Turns ordinary APIs into paid OKX Marketplace-ready A2MCP service packages."
        ),
        capabilities=[
            "Analyze FastAPI/OpenAPI services",
            "Recommend paid-call pricing",
            "Generate payment integration assets",
            "Create Marketplace listing files",
            "Run mock payment self-tests",
        ],
        inputs=[
            "Local FastAPI service path",
            "OpenAPI JSON file or URL",
            "Manual endpoint description",
            "Pricing confirmation",
        ],
        outputs=[
            "payment_patch.diff",
            "services.json",
            "agent_card.json",
            "listing.md",
            "test_report.json",
        ],
        okx_fit=[
            "Accelerates ASP onboarding",
            "Expands paid A2MCP provider supply",
            "Demonstrates Agent Payments Protocol adoption",
        ],
    )

    services_path = destination / "services.json"
    agent_card_path = destination / "agent_card.json"
    listing_path = destination / "listing.md"

    services.write_json(services_path)
    agent_card.write_json(agent_card_path)

    env = Environment(
        loader=FileSystemLoader(TEMPLATE_ROOT),
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    listing_template = env.get_template("listing/listing.md.j2")
    listing_path.write_text(
        listing_template.render(profile=profile, pricing=pricing),
        encoding="utf-8",
    )
    return [services_path, agent_card_path, listing_path]
