from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from tools.models import PricingPlan, ServiceProfile


class PatchGenerationError(ValueError):
    """Raised when a service cannot be patched automatically."""


TEMPLATE_ROOT = Path(__file__).resolve().parents[1] / "templates"


def generate_payment_patch(
    profile: ServiceProfile,
    pricing: PricingPlan,
    output_dir: str | Path,
) -> list[Path]:
    if profile.framework.lower() != "fastapi":
        raise PatchGenerationError("Automatic payment patch generation only supports FastAPI services.")
    if not pricing.confirmed:
        raise PatchGenerationError("Pricing must be confirmed before generating payment assets.")

    destination = Path(output_dir)
    generated_dir = destination / "generated" / "fastapi"
    generated_dir.mkdir(parents=True, exist_ok=True)

    context = _context(profile, pricing)
    env = Environment(
        loader=FileSystemLoader(TEMPLATE_ROOT),
        autoescape=False,
        trim_blocks=True,
        lstrip_blocks=True,
    )

    outputs = {
        "fastapi/payment_adapter.py.j2": generated_dir / "payment_adapter.py",
        "fastapi/payment_middleware.py.j2": generated_dir / "payment_middleware.py",
        "fastapi/env.example.j2": generated_dir / ".env.example",
        "fastapi/test_payment.py.j2": generated_dir / "test_payment.py",
    }

    generated_paths = []
    for template_name, path in outputs.items():
        template = env.get_template(template_name)
        path.write_text(template.render(**context), encoding="utf-8")
        generated_paths.append(path)

    patch_path = destination / "payment_patch.diff"
    patch_path.write_text(_patch_diff(context), encoding="utf-8")
    generated_paths.insert(0, patch_path)
    return generated_paths


def _context(profile: ServiceProfile, pricing: PricingPlan) -> dict[str, str]:
    endpoint = profile.selected_endpoint
    return {
        "service_name": profile.service_name,
        "service_id": profile.service_id,
        "endpoint_path": endpoint.path,
        "endpoint_method": endpoint.method,
        "amount": str(pricing.amount),
        "currency": pricing.currency,
        "payment_mode": pricing.payment_mode,
        "real_mode_asset": pricing.real_mode_asset,
        "mock_paid_header": "x-mock-paid",
    }


def _patch_diff(context: dict[str, str]) -> str:
    endpoint = context["endpoint_path"]
    method = context["endpoint_method"].lower()
    service_id = context["service_id"]
    return f"""diff --git a/payment_adapter.py b/payment_adapter.py
new file mode 100644
--- /dev/null
+++ b/payment_adapter.py
@@
+# Generated by Dragon MCP Pay Agent for {service_id}.
+# Provides MockPaymentAdapter and an opt-in OkxPaymentAdapter boundary.
+
diff --git a/main.py b/main.py
--- a/main.py
+++ b/main.py
@@
+from fastapi import Depends
+from payment_adapter import require_payment
@@
+# Protect {method.upper()} {endpoint} with dependencies=[Depends(require_payment)].
+# Example: @app.{method}("{endpoint}", dependencies=[Depends(require_payment)])
"""

